version: '3.1'

services:
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    volumes:
      - $HOME/MySqlData:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
